# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=200, verbose_name='\u6587\u7ae0 url \u5730\u5740')),
                ('email', models.EmailField(max_length=254, verbose_name='\u7528\u6237\u7559\u4e0b\u7684 email')),
                ('guid', models.CharField(max_length=100, verbose_name='GUID')),
                ('ip', models.CharField(max_length=20, verbose_name='\u8bbf\u95ee\u8005\u7684 IP \u5730\u5740')),
                ('product_id', models.CharField(max_length=100, verbose_name='\u6839\u636e URL \u63d0\u53d6\u7684 id')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'jd_comment_analysis_user',
            },
        ),
        migrations.CreateModel(
            name='JDCommentAnalysis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('guid', models.CharField(max_length=100, verbose_name='GUID')),
                ('email', models.EmailField(default='', max_length=50, verbose_name='\u7528\u6237\u7559\u4e0b\u7684 email')),
                ('product_id', models.BigIntegerField(verbose_name='\u4eac\u4e1c\u5546\u54c1\u7684 id')),
                ('item_name', models.CharField(max_length=200, verbose_name='\u4eac\u4e1c\u5546\u57ce\u5546\u54c1\u7684\u540d\u79f0')),
                ('content', models.TextField(verbose_name='\u5b8c\u6574\u7684\u5206\u6790\u7ed3\u679c\u5c55\u793a')),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-create_time'],
                'db_table': 'jd_comment_analysis_result',
            },
        ),
        migrations.CreateModel(
            name='JDVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jd_url', models.CharField(default='', max_length=200, verbose_name='\u4eac\u4e1c\u5546\u57ce\u5546\u54c1\u7684 url \u94fe\u63a5')),
                ('ip', models.CharField(max_length=20, verbose_name='\u8bbf\u95ee\u8005\u7684 IP \u5730\u5740')),
                ('ip_address', models.CharField(default=None, max_length=200, verbose_name='IP \u5bf9\u5e94\u7684\u5730\u5740')),
                ('visit_time', models.DateTimeField(verbose_name='\u8bbf\u95ee\u7684\u65f6\u95f4')),
                ('user_agent', models.TextField(default='', max_length=1000, verbose_name='\u8bbf\u95ee\u8005\u7684 HTTP_USER_AGENT')),
                ('ip_hight_success', models.CharField(default='', max_length=10, verbose_name='\u67e5\u8be2 IP \u9ad8\u7cbe\u5ea6\u5b9a\u4f4d\u662f\u5426\u6210\u529f')),
                ('ip_hight_address', models.CharField(default='', max_length=200, verbose_name='IP \u5bf9\u5e94\u7684\u9ad8\u7cbe\u5ea6\u5730\u5740')),
                ('ip_confidence', models.FloatField(default=0, verbose_name='IP \u9ad8\u7cbe\u5ea6\u67e5\u8be2\u7ed3\u679c\u7684\u53ef\u4fe1\u5ea6')),
                ('ip_hight_radius', models.IntegerField(default=-1, verbose_name='IP \u9ad8\u7cbe\u5ea6\u67e5\u8be2\u7ed3\u679c\u7684\u504f\u79fb\u534a\u5f84')),
                ('ip_hight_lat', models.FloatField(default=-1, verbose_name='IP \u9ad8\u7cbe\u5ea6\u67e5\u8be2\u7ecf\u5ea6')),
                ('ip_hight_long', models.FloatField(default=-1, verbose_name='IP \u9ad8\u7cbe\u5ea6\u67e5\u8be2\u7eac\u5ea6')),
            ],
            options={
                'db_table': 'jd_visit',
            },
        ),
    ]
